/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HWF_H_RPCGEN
#define _HWF_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HWF_PROG 1
#define HWF_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HWF 11
extern  char ** hwf_1(long *, CLIENT *);
extern  char ** hwf_1_svc(long *, struct svc_req *);
extern int hwf_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HWF 11
extern  char ** hwf_1();
extern  char ** hwf_1_svc();
extern int hwf_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HWF_H_RPCGEN */
