/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hwf.h"
#include <time.h>
#include <linux/kernel.h>
#include <sys/sysinfo.h>    // sysinfo
#include <stdio.h>
#include <unistd.h>     //sysconf
#include <stdlib.h>
#include <rpc/rpc.h>
#include <sys/types.h>

char **
hwf_1_svc(long *argp, struct svc_req *rqstp)
{
    static char * result;
    static char buf_load[1000];
    long double a[4], b[4], loadavg;
    FILE *fp;
    char ** output;
    int i =0;
    
    
    
    
    long minute = 60;
    long hour = minute * 60;
    long day = hour * 24;
    double megabyte = 1024 * 1024;
    
    
    struct sysinfo si;
    sysinfo (&si);
    
    
    time_t mytime;
    mytime = time(NULL);
    
    
    printf ("system uptime : %ld days, %ld:%02ld:%02ld\n", si.uptime / day, (si.uptime % day) / hour, (si.uptime % hour) / minute, si.uptime % minute);
    printf ("Available RAM   : %5.1f MB\n", si.totalram / megabyte);
    printf ("Free RAM   : %5.1f MB\n", si.freeram / megabyte);
    printf ("Ram Usage : %5.1f MB\n", (si.totalram-si.freeram)/megabyte);
    
    //  while(i <10)
    // {
    fp = fopen("/proc/stat","r");
    fscanf(fp,"%*s %Lf %Lf %Lf %Lf",&a[0],&a[1],&a[2],&a[3]);
    fclose(fp);
    sleep(1);
    
    fp = fopen("/proc/stat","r");
    fscanf(fp,"%*s %Lf %Lf %Lf %Lf",&b[0],&b[1],&b[2],&b[3]);
    fclose(fp);
    
    loadavg = ((b[0]+b[1]+b[2]) - (a[0]+a[1]+a[2])) / ((b[0]+b[1]+b[2]+b[3]) - (a[0]+a[1]+a[2]+a[3]));
    printf("The current CPU utilization(%) is : %Lf\n",loadavg);
    loadavg = loadavg*100;
    // i++;
    // }
    
    sprintf(buf_load,"Number of processes running on Server:%d\nTotal RAM on Server: %5.1f\nFree RAM on Server: %5.1f\n Ram Usage: %5.1f\nServer system Uptime:%ld days, %ld:%02ld:%02ld\n1 minute load average:%ld\n5 minute load average:%ld\n15 minute load average:%ld\nThe current Server CPU utilization(in %) is: %Lf\nServer current Date and Time:%s\n",si.procs, si.totalram / megabyte, si.freeram / megabyte,(si.totalram-si.freeram)/megabyte, si.uptime / day, (si.uptime % day) / hour,
            (si.uptime % hour) / minute, si.uptime % minute, si.loads[0],si.loads[1],si.loads[2],loadavg,ctime(&mytime));
    
    result =  buf_load;
    puts(buf_load);
    
    return &result;
    
}
